--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."CART_SEQ"  MINVALUE 1 MAXVALUE 111111111111 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."COMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 2469 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."ITEM_SEQ"  MINVALUE 1 MAXVALUE 1111111111 INCREMENT BY 1 START WITH 3475 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LINK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."LINK_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."MENU_SEQ"  MINVALUE 1 MAXVALUE 1111111111 INCREMENT BY 1 START WITH 171 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."ORDER_SEQ"  MINVALUE 1 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 50 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROOT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."ROOT_SEQ"  MINVALUE 1 MAXVALUE 555555 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OS2"."USER_SEQ"  MINVALUE 1 MAXVALUE 56555555 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARTS
--------------------------------------------------------

  CREATE TABLE "OS2"."CARTS" 
   (	"CART_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"REG_DATE" TIMESTAMP (6), 
	"ROOT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "OS2"."COMMENTS" 
   (	"ID" NUMBER, 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"SCORE" NUMBER, 
	"REG_DATE" TIMESTAMP (6), 
	"PATH" VARCHAR2(200 BYTE), 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "OS2"."ITEMS" 
   (	"NAME" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"ID" NUMBER, 
	"PRICE" NUMBER, 
	"DISCOUNT" NUMBER, 
	"NUM_SOLD" NUMBER DEFAULT 0, 
	"PATH" VARCHAR2(500 BYTE), 
	"IMAGE_PATH" VARCHAR2(500 BYTE), 
	"SCORE" VARCHAR2(200 BYTE) DEFAULT 0, 
	"REG_DATE" TIMESTAMP (6), 
	"NUM_STOCK" NUMBER DEFAULT 0, 
	"NUM_VIEW" NUMBER DEFAULT 0, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LINKS
--------------------------------------------------------

  CREATE TABLE "OS2"."LINKS" 
   (	"ROOT_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"LINK" VARCHAR2(500 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU_DEPTH1
--------------------------------------------------------

  CREATE TABLE "OS2"."MENU_DEPTH1" 
   (	"NAME" VARCHAR2(255 BYTE), 
	"ID" VARCHAR2(255 BYTE), 
	"PARENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU_DEPTH2
--------------------------------------------------------

  CREATE TABLE "OS2"."MENU_DEPTH2" 
   (	"NAME" VARCHAR2(255 BYTE), 
	"ID" VARCHAR2(255 BYTE), 
	"PARENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU_ROOT
--------------------------------------------------------

  CREATE TABLE "OS2"."MENU_ROOT" 
   (	"NAME" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"ID" NUMBER, 
	"STYLE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "OS2"."ORDERS" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ITEMS" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"PG" VARCHAR2(20 BYTE), 
	"PG_NAME" VARCHAR2(100 BYTE), 
	"REQUESTED_AT" TIMESTAMP (6), 
	"NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "OS2"."USERS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View COMMENTS_WITH_USER_NAME
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "OS2"."COMMENTS_WITH_USER_NAME" ("ID", "CONTENT", "SCORE", "REG_DATE", "PATH", "USER_ID", "USER_NAME") AS 
  SELECT C."ID",C."CONTENT",C."SCORE",C."REG_DATE",C."PATH",C."USER_ID", U.NAME AS USER_NAME
FROM COMMENTS C
JOIN USERS U ON C.USER_ID = U.ID
;
--------------------------------------------------------
--  DDL for View ITEMS_WITH_SCORE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "OS2"."ITEMS_WITH_SCORE" ("NAME", "CONTENT", "ID", "PRICE", "DISCOUNT", "NUM_SOLD", "PATH", "IMAGE_PATH", "USER_ID", "SCORE", "REG_DATE", "NUM_STOCK", "NUM_VIEW", "USER_NAME") AS 
  SELECT 
    NAME, i.CONTENT, i.ID, i.PRICE, i.DISCOUNT, i.NUM_SOLD, i.PATH, i.IMAGE_PATH, i.USER_ID, i.SCORE, i.REG_DATE, i.NUM_STOCK, i.NUM_VIEW, (SELECT NAME FROM USERS u WHERE ID = i.USER_ID) as USER_NAME
FROM ITEMS i
;
--------------------------------------------------------
--  DDL for View ITEMS_WITH_SCORE2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "OS2"."ITEMS_WITH_SCORE2" ("NAME", "ID", "PRICE", "DISCOUNT", "NUM_SOLD", "PATH", "IMAGE_PATH", "USER_ID", "SCORE", "REG_DATE", "NUM_STOCK", "NUM_VIEW", "NUM_COMMENT", "AVG_SCORE", "SUM_SCORE", "USER_NAME") AS 
  SELECT 
    i.NAME, i.ID, i.PRICE, i.DISCOUNT, i.NUM_SOLD, i.PATH, i.IMAGE_PATH, i.USER_ID, i.SCORE, i.REG_DATE, i.NUM_STOCK, i.NUM_VIEW,
    COUNT(c.PATH) AS NUM_COMMENT,
    ROUND(NVL(AVG(c.SCORE), 0), 1) AS AVG_SCORE,
    NVL(SUM(c.SCORE), 0) AS SUM_SCORE,
    u.NAME AS USER_NAME
FROM ITEMS i
LEFT JOIN COMMENTS c ON c.PATH LIKE '/' || i.ID || '%'
LEFT JOIN USERS u ON u.ID = i.USER_ID
GROUP BY i.NAME, i.ID, i.PRICE, i.DISCOUNT, i.NUM_SOLD, i.PATH, i.IMAGE_PATH, i.SCORE, i.REG_DATE, i.NUM_STOCK, i.NUM_VIEW, i.USER_ID, u.NAME
;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OS2"."ORDERS_PK" ON "OS2"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OS2"."USERS_PK" ON "OS2"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OS2"."ORDERS_PK" ON "OS2"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OS2"."USERS_PK" ON "OS2"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARTS
--------------------------------------------------------

  ALTER TABLE "OS2"."CARTS" MODIFY ("CART_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "OS2"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OS2"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "OS2"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OS2"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
